#################
# HNI - Staging #
#################
[staging]
146.190.19.190 name=hni-toi-staging-ams3-01

[staging:vars]
server_environment_name=staging
ansible_python_interpreter=/usr/bin/python3

####################
# HNI - Acceptance #
####################
[acceptance]
134.209.201.154 name=hni-toi-acceptance-ams3-01

[acceptance:vars]
server_environment_name=acceptance
ansible_python_interpreter=/usr/bin/python3

####################
# HNI - Production #
####################
[production]
178.62.207.134 name=hni-toi-production-ams3-01

[production:vars]
server_environment_name=production
ansible_python_interpreter=/usr/bin/python3

##########
# Groups #
##########
[app:children]
staging
acceptance
production
