export const MAX_Z_INDEX = 9999

export const NAVIGATION_OVERLAY_Z_INDEX = MAX_Z_INDEX - 1
export const MOBILE_OVERLAY_Z_INDEX = MAX_Z_INDEX - 2
export const FOOTER_Z_INDEX = MAX_Z_INDEX - 3
export const SWITCH_SERVER_Z_INDEX = MAX_Z_INDEX

export const STATIC_HEADER_Z_INDEX = MAX_Z_INDEX + 1
