---
- name: nextjs | docker | start
  docker_container:
    name: "nextjs"
    image: ghcr.io/lifelynl/hni-toi-nextjs:{{ tag }}-{{ server_environment_name }}
    state: started
    restart_policy: always
    recreate: true
    keep_volumes: no
    env: "{{ app.env|combine(app.nextjs.env)|combine({'NODE_ENV': 'production', 'VIRTUAL_HOST': app.web.url, 'LETSENCRYPT_HOST': app.web.url}) }}"
    networks:
      - name: "app-network"
        aliases:
          - nextjs
  tags: [nextjs, deploy]
