---
- name: strapi | docker | start
  docker_container:
    name: "strapi"
    image: ghcr.io/lifelynl/hni-toi-strapi:{{ tag }}
    state: started
    restart_policy: always
    keep_volumes: no
    recreate: true
    env: "{{ app.env|combine({'NODE_ENV': 'production', 'VIRTUAL_HOST': app.web.api_url, 'VIRTUAL_PATH': '/', 'VIRTUAL_DEST': '/', 'LETSENCRYPT_HOST': app.web.api_url}) }}"
    networks:
      - name: "app-network"
        aliases:
          - strapi
  tags: [strapi, deploy]
